import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatChipsModule } from '@angular/material/chips';
import { MatMenuModule } from '@angular/material/menu';
import { MatDividerModule } from '@angular/material/divider';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { Observable, combineLatest } from 'rxjs';
import { map, startWith, debounceTime } from 'rxjs/operators';
import { ItineraryService } from '../../../core/services/itinerary.service';
import { Itinerary } from '../../../core/models/itinerary.model';
import { AuthService } from '../../../core/services/auth.service';
import { Router } from '@angular/router';

import { LoaderComponent } from '../../../shared/components/loader/loader.component';
import { EmptyStateComponent } from '../../../shared/components/empty-state/empty-state.component';

@Component({
  selector: 'app-itinerary-list',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    ReactiveFormsModule,
    MatCardModule,
    MatButtonModule,
    MatIconModule,
    MatInputModule,
    MatChipsModule,
    MatMenuModule,
    MatDividerModule,
    MatSnackBarModule,

    LoaderComponent,
    EmptyStateComponent
  ],
  templateUrl: './itinerary-list.component.html',
  styleUrls: ['./itinerary-list.component.scss']
})
export class ItineraryListComponent implements OnInit {
  itineraries$!: Observable<Itinerary[]>;
  filteredItineraries$!: Observable<Itinerary[]>;
  searchControl = new FormControl('');
  loading = true;

  currentUserEmail: string | undefined = '';

  constructor(
    private itineraryService: ItineraryService,
    private snackBar: MatSnackBar,
    private authService: AuthService,
    private router: Router
  ) {
    const user = this.authService.getCurrentUser();
    // The backend stores email in 'contact_info' or 'email' depending on the model, 
    // but auth.service.ts maps it to User interface which has 'email'.
    // Let's check the User interface or just try access email.
    // Looking at auth.service.ts register/loadAuthState, it seems 'email' is the property on the frontend User model.
    this.currentUserEmail = user?.email;
  }

  logout(): void {
    this.authService.logout();
    this.router.navigate(['/']);
  }

  ngOnInit(): void {
    this.itineraries$ = this.itineraryService.getAll();

    setTimeout(() => this.loading = false, 1000);

    this.filteredItineraries$ = combineLatest([
      this.itineraries$,
      this.searchControl.valueChanges.pipe(
        startWith(''),
        debounceTime(300)
      )
    ]).pipe(
      map(([itineraries, search]) => {
        if (!search) return itineraries;
        const term = search.toLowerCase();
        return itineraries.filter(i =>
          i.destination.toLowerCase().includes(term)
        );
      })
    );
  }

  deleteItinerary(id: string): void {
    if (confirm('Are you sure you want to delete this itinerary?')) {
      this.itineraryService.delete(id).subscribe(() => {
        this.snackBar.open('Itinerary deleted successfully', 'Close', { duration: 3000 });
      });
    }
  }

  formatDate(date: Date): string {
    return new Date(date).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric'
    });
  }

  getDuration(itinerary: Itinerary): number {
    const start = new Date(itinerary.startDate);
    const end = new Date(itinerary.endDate);
    const diff = end.getTime() - start.getTime();
    return Math.ceil(diff / (1000 * 60 * 60 * 24)) + 1;
  }

  getBudgetPercentage(itinerary: Itinerary): number {
    return Math.min((itinerary.totalEstimatedCost / itinerary.budget) * 100, 100);
  }

  getDestinationImage(itinerary: Itinerary): string {
    // 1. Check for stored media (generated by backend/service)
    if (itinerary.media && itinerary.media.length > 0) {
      const url = itinerary.media[0];
      // Ensure proper CSS format
      return url.startsWith('url(') ? url : `url(${url})`;
    }

    // 2. Fallback to hardcoded list for specific cities
    const images: Record<string, string> = {
      'Paris': 'url(https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=500)',
      'Tokyo': 'url(https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=500)',
      'New York': 'url(https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=500)',
      'London': 'url(https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=500)',
      'Rome': 'url(https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=500)'
    };

    if (images[itinerary.destination]) {
      return images[itinerary.destination];
    }

    // 3. Last resort dynamic image
    const safeDest = encodeURIComponent(itinerary.destination);
    return `url(https://loremflickr.com/800/600/${safeDest}/all)`;
  }
}