import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { FormControl, FormsModule, ReactiveFormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatChipsModule } from '@angular/material/chips';
import { MatMenuModule } from '@angular/material/menu';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { Observable, combineLatest } from 'rxjs';
import { map, startWith, debounceTime } from 'rxjs/operators';
import { ItineraryService } from '../../../core/services/itinerary.service';
import { Itinerary } from '../../../core/models/itinerary.model';

import { LoaderComponent } from '../../../shared/components/loader/loader.component';
import { EmptyStateComponent } from '../../../shared/components/empty-state/empty-state.component';

@Component({
  selector: 'app-itinerary-list',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    ReactiveFormsModule,
    MatCardModule,
    MatButtonModule,
    MatIconModule,
    MatInputModule,
    MatChipsModule,
    MatMenuModule,
    MatSnackBarModule,
    FormsModule,

    LoaderComponent,
    EmptyStateComponent
  ],
  templateUrl: './itinerary-list.component.html',
  styleUrls: ['./itinerary-list.component.scss']
})
export class ItineraryListComponent implements OnInit {
  itineraries$!: Observable<Itinerary[]>;
  filteredItineraries$!: Observable<Itinerary[]>;
  searchControl = new FormControl('');
  loading = true;

  constructor(
    private itineraryService: ItineraryService,
    private snackBar: MatSnackBar,
    private router:Router
  ) { }

  ngOnInit(): void {
    this.itineraries$ = this.itineraryService.getAll();

    setTimeout(() => this.loading = false, 1000);

    this.filteredItineraries$ = combineLatest([
      this.itineraries$,
      this.searchControl.valueChanges.pipe(
        startWith(''),
        debounceTime(300)
      )
    ]).pipe(
      map(([itineraries, search]) => {
        if (!search) return itineraries;
        const term = search.toLowerCase();
        return itineraries.filter(i =>
          i.destination.toLowerCase().includes(term)
        );
      })
    );
  }

  deleteItinerary(id: string): void {
    if (confirm('Are you sure you want to delete this itinerary?')) {
      this.itineraryService.delete(id).subscribe(() => {
        this.snackBar.open('Itinerary deleted successfully', 'Close', { duration: 3000 });
      });
    }
  }

  formatDate(date: Date): string {
    return new Date(date).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric'
    });
  }

  getDuration(itinerary: Itinerary): number {
    const start = new Date(itinerary.startDate);
    const end = new Date(itinerary.endDate);
    const diff = end.getTime() - start.getTime();
    return Math.ceil(diff / (1000 * 60 * 60 * 24)) + 1;
  }

  getBudgetPercentage(itinerary: Itinerary): number {
    return Math.min((itinerary.totalEstimatedCost / itinerary.budget) * 100, 100);
  }

  getDestinationImage(itinerary: Itinerary): string {
    // 1. Check for stored media (generated by backend/service)
    if (itinerary.media && itinerary.media.length > 0) {
      const url = itinerary.media[0];
      // Ensure proper CSS format
      return url.startsWith('url(') ? url : `url(${url})`;
    }

    // 2. Fallback to hardcoded list for specific cities
    const images: Record<string, string> = {
      'Paris': 'url(https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=500)',
      'Tokyo': 'url(https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=500)',
      'New York': 'url(https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=500)',
      'London': 'url(https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=500)',
      'Rome': 'url(https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=500)'
    };

    if (images[itinerary.destination]) {
      return images[itinerary.destination];
    }

    // 3. Last resort dynamic image
    const safeDest = encodeURIComponent(itinerary.destination);
    return `url(https://loremflickr.com/800/600/${safeDest},travel/all)`;
  }

  destination = '';
  budget!: number;

  showDropdown = false;
  showPopup = false;

  startDate = '';
  endDate = '';
  members = 1;

places = ['Goa', 'Kerala', 'Paris', 'Tokyo', 'New York', 'Dubai', 'Maldives', 'Bali', 'London', 'Rome', 'Barcelona', 'Sydney', 'Singapore', 'Kodaikanal', 'Manali'];

  filteredPlaces: string[] = [...this.places];

  
  filterPlaces() {
    this.filteredPlaces = this.places.filter(place =>
      place.toLowerCase().includes(this.destination.toLowerCase())
    );
  }
  selectPlace(place: string) {
    this.destination = place;
    this.showDropdown = false;
  }
  errorMessage: string = '';


details1page() {
  if (!this.destination && !this.budget) {
    this.errorMessage = '*Please enter destination and budget';
    return;
  }

  if (!this.destination) {
    this.errorMessage = '*Please select a destination';
    return;
  }

  if (!this.budget) {
    this.errorMessage = '*Please enter your budget';
    return;
  }

  // ✅ clear error if valid
  this.errorMessage = '';

  this.router.navigate(['/itinerary-details-page'], {
    queryParams: {
      destination: this.destination,
      budget: this.budget
    }
  });
}



  // destinationError = false;
  // budgetError = false;

  // ✅ Open popup with validation
//   detailspage() {
//   this.destinationError = !this.destination;
//   this.budgetError = !this.budget;

//   if (this.destinationError || this.budgetError) return;

//   this.showPopup = true;
// }


}